name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: make docker-build
    - name: Run tests
      run: make docker-runtest-all
    - uses: actions/checkout@v2
    - uses: ./
      id: stale
      with:
        stale-issue-message: 'This issue is stale'
        stale-pr-message: 'This PR is stale'
        debug-only: true
    - name: Print outputs
      run: echo ${{ join(steps.stale.outputs.*, ',') }}
